### PR TITLE
Fix the AllowedMethodsLoader when using sf 3.0

### LINKED ISSUE #1412: "Allowed Http Methods Listener" not working on Symfony 3
Allow header does not appear on responses using Symfony version 3.03. I have another project running on Symfony version 2.8.1 where the listener works fine. 
The config.yml line where I enable it in both projects:
```yml
allowed_methods_listener: true
``` 
The headers that cURL outputs not containing the Allow header;
```HTTP
Host: localhost:8000
Connection: close
X-Powered-By: PHP/5.6.19-1+deb.sury.org~trusty+1
Cache-Control: no-cache
Content-Type: application/json
X-Debug-Token: b5b884
X-Debug-Token-Link: /app_dev.php/_profiler/b5b884
Date: Sun, 03 Apr 2016 18:10:52 GMT

### PR DESCRIPTION
**Pull request by Ener-Getick**
Fixes #1412 and adds tests for the AllowedMethodsListener.

### CODE REVIEW

File: Response/AllowedMethodsLoader/AllowedMethodsRouterLoader.php [hunk 1]
```diff
@@ -79,15 +79,10 @@ public function warmUp($cacheDir)
...
-            if (isset($requirements['_method'])) {
-                $methods = explode('|', $requirements['_method']);
-                $processedRoutes[$route->getPath()]['methods'] = array_merge(
-                    $processedRoutes[$route->getPath()]['methods'],
-                    $methods
-                );
-            }
+            $processedRoutes[$route->getPath()]['methods'] = array_merge(
+                $processedRoutes[$route->getPath()]['methods'],
+                $route->getMethods()
```
Comment (Ener-Getick) [inline Response/AllowedMethodsLoader/AllowedMethodsRouterLoader.php]: available since 2.2, so there is no problem

File: Tests/Functional/AllowedMethodsTest.php [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+namespace FOS\RestBundle\Tests\Functional;
+
+/**
+ * @author Ener-Getick <egetick@gmail.com>
+ */
+class AllowedMethodsTest extends WebTestCase
+{
+    public function setUp()
+    {
+        $this->client = $this->createClient(array('test_case' => 'ParamFetcher'));
```
Comment (xabbuh) [inline Tests/Functional/AllowedMethodsTest.php]: Looks a bit strange to search for the configuration in the `ParamFetcher` test. Let's use a dedicated section instead (makes it easier to find the right test case).

Comment (Ener-Getick) [inline Tests/Functional/AllowedMethodsTest.php]: I think we have already a lot of test cases (maybe we should reorganize that later) but you're right, that's a bit confusing...

Comment (Ener-Getick) [inline Tests/Functional/AllowedMethodsTest.php]: updated :smile:

File: Tests/Functional/app/ParamFetcher/config.yml [hunk 3]
```diff
@@ -4,6 +4,7 @@ imports:
 framework:
     serializer:
         enabled: true
-        
+
 fos_rest:
     param_fetcher_listener: true
+    allowed_methods_listener: true
```
Comment (xabbuh) [inline Tests/Functional/app/ParamFetcher/config.yml]: The changes in this file should be reverted.

Comment (Ener-Getick) [inline Tests/Functional/app/ParamFetcher/config.yml]: done

File: Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml [hunk 4]
```diff
@@ -21,3 +21,12 @@ test_param_fetcher_test:
...
     resource: FOS\RestBundle\Tests\Functional\Bundle\TestBundle\Controller\ArticleController
     type:     rest
+
+test_allowed_methods1:
+    path:     /allowed-methods
+    methods: ['GET', 'LOCK']
+
+test_allowed_methods2:
+    path:     /allowed-methods
+    defaults: { _controller: TestBundle:AllowedMethods:index }
```
Comment (xabbuh) [inline Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml]: What about adding this to the other route for consistency too? I am sure this is my last remark here. ;)

Comment (Ener-Getick) [inline Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml]: done ;)

**Comment by xabbuh** [comment]
Thank you @Ener-Getick.
