### PR TITLE
  Fix a bug in the ParamFetcher

### LINKED ISSUE #1255: Bug in Version 1.7.3?
Since the scope attribute was removed from the service, the ParamFetcher does not init the params property again for the sub request, so if an exception is triggered inside the paramFetcher instead of rendering the exception response the paramfetcher throws the same exception again

### PR DESCRIPTION
**Pull request by Ener-Getick**
Fixed #1255

### CODE REVIEW

File: Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+        $paramsBefore = $fetcher->all();
+
+        $newRequest = new Request();
+        $newRequest->query = $request->query;
+        $newRequest->request = $request->request;
+        $newRequest->attributes->set('_controller', sprintf('%s::paramsAction', __CLASS__));
+        $response = $this->container->get('http_kernel')->handle($newRequest, HttpKernelInterface::SUB_REQUEST, false);
+
+        // FIXME: The controller is not reinitialized after a sub request.
+        // $paramsAfter = $fetcher->all(false);
```
Comment (Ener-Getick) [inline Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php]: I'm not sure if this is a regression or not and how we can fix it...

Comment (stof) [inline Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php]: I don't understand what you mean

Comment (stof) [inline Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php]: OK, found the issue: ``$this->controller`` is also scoped to the request

Comment (Ener-Getick) [inline Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php]: If we call ``ParamFetcher::getParams`` after calling ``Kernel::handle`` the params returned are those of the controller of the sub request.

**Comment by Ener-Getick** [comment]
A solution might be to instantiate a ``ParamFetcher`` for each controller in the ``ParamFetcherListener`` and force the user to get it as an argument..

File: Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php (hunk 1 above)
Comment (stof) [inline Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php]: exactly my point: ``$this->controller`` needs to be reset to the master one after leaving the subrequest

Comment (Ener-Getick) [inline Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php]: Yeah but the paramfetcher can also receive params dynamically... IMO the best solution is to instantiate a param fetcher for each controller in the listener and forces the user to use the request attributes.

Comment (Ener-Getick) [inline Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php]: For bc we can create a ParamFetcherStack which would receive the current ParamFetcher but it would be bugged in part.

**Comment by stof** [comment]
@Ener-Getick this would mean dropping the support for the injection as a service, which is not good as a bugfix.

**Comment by Ener-Getick** [comment]
We can also use a ``ParameterBag`` which would use ``spl_object_hash`` internally to match the current params but I don't know the performances of this function...

**Comment by Ener-Getick** [comment]
What do you think about this new solution @stof ?

**Comment by lsmith77** [comment]
looks good to me.

reviewed

**Comment by lsmith77** [comment]
Status: Reviewed

**Comment by lsmith77** [comment]
BTW .. just noticed that carson doesn't seen to see it when one edits a comment.

**Comment by Ener-Getick** [comment]
Yeah it only works when you submit a comment (may have a weird behavior if the edited comments were supported)
