### PR TITLE
fix route generator not ignoring body param converters

### LINKED ISSUE #1198: Make a better marriage between body and param converter
From the [docs](http://symfony.com/doc/current/bundles/FOSRestBundle/request_body_converter_listener.html):

> You will probably want to disable the automatic route generation (@NoRoute) for routes using the body converter, and instead define the routes manually to avoid having the deserialized, type hinted objects ($post in this example) appear in the route as a parameter.

And that's unfortunately true, I have to redefine entirely the route:

``` php
/**
 * @param Server     $server
 * @param ServerStat $stat
 *
 * @Route("/servers/{server}/stats")
 * @Security("is_granted('ROLE_ADMIN')")
 * @ParamConverter("stat", converter="fos_rest.request_body")
 *
 * @return View
 */
public function postAction(Server $server, ServerStat $stat)
{
}
```

That works, but it is very painful IMHO.

There is any way to improve this management in order to avoid this?

If you can give me some clue, I could maybe work on it. :+1:

### PR DESCRIPTION
**Pull request by tonivdv**
### This is an update on PR #1771 with the missing test case. All credits should go to @Parent5446 

When fetching a list of function parameters from a controller action
for use as URL parameters, check for the @ParamConverter
annotation. If a parameter has the annotation with the
"fos_rest.request_body" converter, then ignore it and do not include
it in the list of parameters (thus removing it from the URL).

This allows automatic route generation and ParamConverter to co-exist,
as otherwise a parameter that is expected to be derived from the body
would also be included as a URL parameter, requiring the developer to
manually specify the route.

fixes #1198

### CODE REVIEW

**Comment by tonivdv** [comment]
I was not able to run the php-cs fixer. Somehow it fails on my machine :/ And there is no doc on how it should be executed. It would be cool to have a docker config for that to avoid this kind of situations ;)

**Comment by tonivdv** [comment]
ping @GuilhemN

**Comment by tonivdv** [comment]
Fixed the CS issue with the provided diff by styleci 👍

File: Routing/Loader/Reader/RestActionReader.php [hunk 1]
```diff
@@ -475,6 +475,17 @@ private function getMethodArguments(\ReflectionMethod $method)
         // ignore all query params
         $params = $this->paramReader->getParamsFromMethod($method);
 
+        // check if a parameter is coming from the request body
+        $ignoreParameters = [];
+        if (class_exists('Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\ParamConverter')) {
```
Comment (xabbuh) [inline Routing/Loader/Reader/RestActionReader.php]: let's use the `class` constant here

File: Tests/Routing/Loader/RestRouteLoaderTest.php [hunk 2]
```diff
@@ -370,6 +370,19 @@ public function testRequestTypeHintsIgnoredCorrectly()
...
+     * @see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1198
+     */
+    public function testParamConverterIsIgnoredInRouteGenerationCorrectly()
+    {
+        $collection = $this->loadFromControllerFixture('ParamConverterController');
+
+        $this->assertNotNull($collection->get('post_something'), 'route for "post_something" does not exist');
+        $this->assertEquals('/somethings.{_format}', $collection->get('post_something')->getPath());
+
+        $this->assertTrue(true);
```
Comment (xabbuh) [inline Tests/Routing/Loader/RestRouteLoaderTest.php]: this should be removed

File: Tests/Routing/Loader/RestRouteLoaderTest.php [hunk 3]
```diff
@@ -370,6 +370,19 @@ public function testRequestTypeHintsIgnoredCorrectly()
...
 
+    /**
+     * @see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1198
+     */
+    public function testParamConverterIsIgnoredInRouteGenerationCorrectly()
+    {
+        $collection = $this->loadFromControllerFixture('ParamConverterController');
+
+        $this->assertNotNull($collection->get('post_something'), 'route for "post_something" does not exist');
+        $this->assertEquals('/somethings.{_format}', $collection->get('post_something')->getPath());
```
Comment (xabbuh) [inline Tests/Routing/Loader/RestRouteLoaderTest.php]: should be `assertSame()`

File: Tests/Routing/Loader/RestRouteLoaderTest.php (hunk 2 above)
Comment (tonivdv) [reply Tests/Routing/Loader/RestRouteLoaderTest.php]: oops

File: Tests/Routing/Loader/RestRouteLoaderTest.php (hunk 3 above)
Comment (tonivdv) [reply Tests/Routing/Loader/RestRouteLoaderTest.php]: Ok. Just copied from previous tests.

File: Routing/Loader/Reader/RestActionReader.php [hunk 4]
```diff
@@ -475,6 +475,17 @@ private function getMethodArguments(\ReflectionMethod $method)
         // ignore all query params
         $params = $this->paramReader->getParamsFromMethod($method);
 
+        // check if a parameter is coming from the request body
+        $ignoreParameters = [];
+        if (class_exists(\Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter::class)) {
```
Comment (xabbuh) [inline Routing/Loader/Reader/RestActionReader.php]: but please also add use case for the classes :)

File: Routing/Loader/Reader/RestActionReader.php [hunk 5]
```diff
@@ -500,6 +511,10 @@ private function getMethodArguments(\ReflectionMethod $method)
                 }
             }
 
+            if (in_array($argument->getName(), $ignoreParameters)) {
```
Comment (xabbuh) [inline Routing/Loader/Reader/RestActionReader.php]: we should also pass `true` as the third argument

File: Routing/Loader/Reader/RestActionReader.php (hunk 4 above)
Comment (tonivdv) [reply Routing/Loader/Reader/RestActionReader.php]: Not sure I understand what you mean, can you elaborate.

Comment (xabbuh) [reply Routing/Loader/Reader/RestActionReader.php]: Oh, I meant `use` statements. 🙈

Comment (tonivdv) [reply Routing/Loader/Reader/RestActionReader.php]: Alright, I prefer that too, but since a lot in the code is with FQN I thought it was some standard or something. Will do that simplification.

Comment (tonivdv) [reply Routing/Loader/Reader/RestActionReader.php]: I changed all FQN in that method so it's cleaned up at the same time.

File: Routing/Loader/Reader/RestActionReader.php [hunk 6]
```diff
@@ -466,21 +472,32 @@ private function getHttpMethodAndResourcesFromMethod(\ReflectionMethod $method,
...
      * Returns readable arguments from method.
      *
-     * @param \ReflectionMethod $method
+     * @param ReflectionMethod $method
      *
-     * @return \ReflectionParameter[]
+     * @return ReflectionParameter[]
      */
-    private function getMethodArguments(\ReflectionMethod $method)
+    private function getMethodArguments(ReflectionMethod $method)
```
[the remark this answers is not in the document]
Comment (tonivdv) [reply Routing/Loader/Reader/RestActionReader.php]: Ah lol. Alright no problem.

[the remark this answers is not in the document]
Comment (tonivdv) [reply Routing/Loader/Reader/RestActionReader.php]: done

**Comment by GuilhemN** [comment]
Thank you @tonivdv for taking care of this!

**Comment by GuilhemN** [comment]
We usually release when there are a significant number of bug fixes/features awaiting (see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1870). I guess we can release 2.4 though, important fixes are awaiting right now. Is it ok for you @xabbuh?

**Comment by xabbuh** [comment]
👍 let's go for it

**Comment by GuilhemN** [comment]
Done, see https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/2.4.0
