### PR TITLE
Fix #1354

### LINKED ISSUE #1354: The template should be a string or extend TemplateReference
Hi,

Error seems appear with SensioFrameworkExtraBundle v3.0.13, and crash all my code.

I hope someone has an idea..

Here is the Stack Trace returned by Symfony

```
Stack Trace
1 - in vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/View.php at line 218   -
    public function setTemplate($template)
    {
        if (!(is_string($template) || $template instanceof TemplateReference)) {
            throw new \InvalidArgumentException('The template should be a string or extend TemplateReference');
        }
        $this->template = $template;

2 - at View ->setTemplate (object(Template)) 
in vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/ViewResponseListener.php at line 122   -
                    $template->set('format', null);
                }
                $view->setTemplate($template);
            }
        }

3 - at ViewResponseListener ->onKernelView (object(GetResponseForControllerResultEvent), 'kernel.view', object(TraceableEventDispatcher)) 
at call_user_func (array(object(ViewResponseListener), 'onKernelView'), object(GetResponseForControllerResultEvent), 'kernel.view', object(TraceableEventDispatcher)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php at line 61   -
        $e = $this->stopwatch->start($this->name, 'event_listener');
        call_user_func($this->listener, $event, $eventName, $this->dispatcher ?: $dispatcher);
        if ($e->isStarted()) {
            $e->stop();
```

### PR DESCRIPTION
**Pull request by Ener-Getick**
This PR fixes #1354.
This issue was introduced in https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/82b8ad65409c99f693088ecbc09c857f01e3b3fa which removes several container parameters.

### CODE REVIEW

File: Controller/Annotations/View.php [hunk 1]
```diff
@@ -47,18 +47,6 @@ class View extends Template
...
     /**
-     * Returns the annotation alias name.
-     *
-     * @return string
-     *
-     * @see Sensio\Bundle\FrameworkExtraBundle\Configuration\ConfigurationInterface
-     */
-    public function getAliasName()
-    {
-        return 'view';
```
Comment (Ener-Getick) [inline Controller/Annotations/View.php]: This was useless IMO and BTW removed a check in SensioFrameworkBundle to not have a ``@View`` annotation and a ``@Template`` annotation at the same time.

File: EventListener/ViewResponseListener.php [hunk 2]
```diff
@@ -135,8 +127,37 @@ public function onKernelView(GetResponseForControllerResultEvent $event)
...
+     * @param Request  $request
+     * @param Template $template
+     * @param object   $controller
+     * @param string   $action
+     *
+     * @return array
+     *
+     * @see \Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::resolveDefaultParameters()
+     */
+    private function getDefaultVars(Template $template = null, $controller, $action)
```
Comment (Ener-Getick) [inline EventListener/ViewResponseListener.php]: This is needed because ``_template_default_vars`` doesn't exist anymore.

File: EventListener/ViewResponseListener.php [hunk 3]
```diff
@@ -116,10 +111,7 @@ public function onKernelView(GetResponseForControllerResultEvent $event)
                 $view->setData($parameters);
             }
 
-            $template = null !== $configuration && $configuration->getTemplate()
-                ? $configuration->getTemplate()
-                : $request->attributes->get('_template');
```
Comment (Ener-Getick) [inline EventListener/ViewResponseListener.php]: ``_template`` now contains the annotation.

File: Tests/EventListener/ViewResponseListenerTest.php [hunk 4]
```diff
@@ -230,36 +234,33 @@ public function testSerializerEnableMaxDepthChecks($enableMaxDepthChecks, $expec
     public function getDataForDefaultVarsCopy()
     {
         return [
-            [true, false, false],
-            [true, true, true],
-            [false, null, true],
```
Comment (Ener-Getick) [inline Tests/EventListener/ViewResponseListenerTest.php]: Not possible anymore.

File: EventListener/ViewResponseListener.php [hunk 5]
```diff
@@ -58,55 +60,48 @@ public function onKernelView(GetResponseForControllerResultEvent $event)
...
 
-        /** @var \FOS\RestBundle\Controller\Annotations\View $configuration */
-        $configuration = $request->attributes->get('_view');
+        $configuration = $request->attributes->get('_template');
 
         $view = $event->getControllerResult();
-        $customViewDefined = true;
         if (!$view instanceof View) {
-            if (!$configuration && !$this->forceView) {
+            if (!$configuration instanceof ViewAnnotation && !$this->forceView) {
```
Comment (xabbuh) [inline EventListener/ViewResponseListener.php]: `$configuration` will now never be an instance of `ViewAnnotation` if our listener is executed before the one from the SensioFrameworkExtraBundle, will it?
