### PR TITLE
get and set ignored classes

### LINKED ISSUE #2090: RestActionReader ignoring user interface in 2.7.0
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2024 introduced ignoring the UserInterface class as controller argument
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/ab328c73cadc1ee7a102bd4b6a90af5a3b213c10/Routing/Loader/Reader/RestActionReader.php#L532-L540

this breaks all configured children from a ``something_user_route`` parent because ignoring it will cause the following condition to be false
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/ab328c73cadc1ee7a102bd4b6a90af5a3b213c10/Routing/Loader/Reader/RestActionReader.php#L275
and without a singular name all children will trigger this exception
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/ab328c73cadc1ee7a102bd4b6a90af5a3b213c10/Routing/Loader/Reader/RestActionReader.php#L255

i do think it's fairy common to have a user entity to be part of a restful path?

anyway, any suggestions how to work around this issue without having to refactor a large amount of controllers?

### PR DESCRIPTION
**Pull request by wickedOne**
allow ignored classes to be set in the rest action reader

fixes #2090

### CODE REVIEW

File: Routing/Loader/Reader/RestActionReader.php [hunk 1]
```diff
@@ -236,6 +251,26 @@ public function getParents()
         return $this->parents;
     }
 
+    /**
+     * Set ignored classes.
```
Comment (Tobion) [inline Routing/Loader/Reader/RestActionReader.php]: some detailed information about what this means is required

File: Routing/Loader/Reader/RestActionReader.php [hunk 2]
```diff
@@ -236,6 +251,26 @@ public function getParents()
...
+    {
+        $this->ignoredClasses = $ignoredClasses;
+    }
+
+    /**
+     * Get ignored classes.
+     *
+     * @return array
+     */
+    public function getIgnoredClasses()
```
Comment (Tobion) [inline Routing/Loader/Reader/RestActionReader.php]: please add return type

File: Routing/Loader/Reader/RestActionReader.php [hunk 3]
```diff
@@ -116,6 +116,21 @@ class RestActionReader
      */
     private $hasMethodPrefix;
 
+    /**
+     * ignore several type hinted arguments.
+     *
+     * @var array
```
Comment (Tobion) [inline Routing/Loader/Reader/RestActionReader.php]: please remove

File: Routing/Loader/Reader/RestActionReader.php [hunk 4]
```diff
@@ -236,6 +251,29 @@ public function getParents()
         return $this->parents;
     }
 
+    /**
+     * Set ignored classes.
+     *
+     * These classes will be ignored for route construction when
+     * type hinted as method argument.
+     *
+     * @param array $ignoredClasses
```
Comment (Tobion) [inline Routing/Loader/Reader/RestActionReader.php]: `@param string[] $ignoredClasses`

File: Routing/Loader/Reader/RestActionReader.php [hunk 5]
```diff
@@ -236,6 +251,29 @@ public function getParents()
...
+     */
+    public function setIgnoredClasses(array $ignoredClasses): void
+    {
+        $this->ignoredClasses = $ignoredClasses;
+    }
+
+    /**
+     * Get ignored classes.
+     *
+     * @return array
```
Comment (Tobion) [inline Routing/Loader/Reader/RestActionReader.php]: `@return string[]`

File: Routing/Loader/Reader/RestActionReader.php [hunk 6]
```diff
@@ -236,6 +251,29 @@ public function getParents()
...
+     */
+    public function getIgnoredClasses(): array
```
Comment (Tobion) [inline Routing/Loader/Reader/RestActionReader.php]: I don't think we need a getter for this. What's the use-case?

Comment (wickedOne) [reply Routing/Loader/Reader/RestActionReader.php]: you might want to use it to exclude a specific class so when the default ignored classes are changed you don't have to update your code.

```php
$reader->setIgnoredClasses(arary_diff($reader->getIgnoredClasses(), [UserInterface::class]));
```

Comment (xabbuh) [reply Routing/Loader/Reader/RestActionReader.php]: What about adding `addIgnoredClass()`/`addIgnoredClasses()` instead then? That would also make the intent more clear IMO when reading the code that calls any of these methods.

Comment (wickedOne) [reply Routing/Loader/Reader/RestActionReader.php]: for this specific use case i actually need to remove an ignored class, but i agree it makes the intent a bit clearer.
do you want me to add a ``addIgnoredClass`` and ``removeIgnoredClass`` method instead of the getter and setter?

Comment (wickedOne) [reply Routing/Loader/Reader/RestActionReader.php]: ping @xabbuh @Tobion do you want me to change the getter / setter to add / remove?

**Comment by Tobion** [comment]
@wickedOne could you change the target to 2.x and rebase? Currently there is a conflict.

**Comment by wickedOne** [comment]
rebased and changed the target.

File: Routing/Loader/Reader/RestActionReader.php [hunk 7]
```diff
@@ -67,6 +67,29 @@ class RestActionReader
...
+        MessageInterface::class,
+        ParamConverter::class,
+        ParamFetcherInterface::class,
+        Request::class,
+        SessionInterface::class,
+        UserInterface::class,
+    ];
+
+    /**
+     * Initializes controller reader.
```
Comment (Tobion) [inline Routing/Loader/Reader/RestActionReader.php:84]: all of this is irrelevant. maybe rebase problem.

Comment (wickedOne) [reply Routing/Loader/Reader/RestActionReader.php]: yes, rebasee problem, sorry for that.
resolved...
